FILES:
  TRAIN:
    PATH: "data/train.csv"
  TEST:
    PATH: "data/test.csv"
  API_KEY:
    PATH: "config_files/secrets.yaml"

categorical_columns:
  - "type"
  - "sector"

target_column: "price"


model_params:
  learning_rate: 0.01
  n_estimators: 300
  max_depth: 5
  loss: "absolute_error"

